version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: scrapy
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./config:/home/node/app/config
    container_name: ts-node-docker
    expose:
      - 4000
    ports:
      - ${PORT}:4000
    command: npm run start
  
  ts-node-service:
    build: # build required again due to how dumb EB works
      context: .
      dockerfile: Dockerfile # 
    depends_on: 
      - ts-node-docker
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./config:/home/node/app/config
    container_name: ts-node-service
    command: npm run start -- changes --forever 60 ${PROFILE}