version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile-azure
    image: scrapy
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./config:/home/node/app/config
    container_name: ts-node-docker
    ports:
      - 80:${PORT}
    command: npm run start
  
  ts-node-service:
    build: # build required again due to how dumb EB works
      context: .
      dockerfile: Dockerfile-azure      
    depends_on: 
      - ts-node-docker
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./config:/home/node/app/config
    container_name: ts-node-service
    command: npm run start -- changes --forever 60 testing