version: '3.7'

services:
  ts-node-docker:
    image: scrapy.azurecr.io/scrapy:latest
    container_name: ts-node-docker
    environment: 
      PORT: 8080
    expose:
      - 8080
    ports:
      - 80:8080
    command: npm run start
  
  ts-node-service:
    image: scrapy.azurecr.io/scrapy:latest
    depends_on: 
      - ts-node-docker
    container_name: ts-node-service
    command: npm run start -- changes --forever 60 testing