version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./config:/home/node/app/config
    container_name: ts-node-docker
    expose:
      - 4000
    ports:
      - ${PORT}:4000
    command: npm run start
    # npm run start -- changes --forever 60 testing & && npm run start &