# serverless.yml

service: scrapy

provider:
  name: aws
  runtime: nodejs10.16.3
  stage: dev
  region: ap-southeast-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'