

service: scrapy

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2

package:
  exclude:
    - node_modules/**
    - src/**  

layers:
  nodeModules:
    path: layer
    compatibleRuntimes:
      - nodejs12.x

functions:
  app:
    handler: index.handler
    layers:
      - {Ref: NodeModulesLambdaLayer}    
    events:
      - http:
          path: /getName
          method: ANY
          cors: true


plugins:
  - serverless-offline

