# serverless.yml

service: scrapy

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2
  memorySize: 1024

functions:
  app:
    handler: src/handler.server
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'